# Setup
title:               Dubu
tagline:             'Blog'
description:         "Dubu's Git Blog."
url:                 https://dubukim.github.io/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              DubuKim
  url:               https://dubukim.github.io/
  email:             3001day@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Comment
comment:
  provider: "disqus"
  disqus: 
    shortname: "super-corini"